server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wang?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wht19970407

  thymeleaf:
    cache: false